# Generated by Django 5.1.1 on 2024-10-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Localizacao',
            new_name='locations',
        ),
    ]
