# Generated by Django 5.1.1 on 2024-11-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_localizacao_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tipo_material', models.CharField(max_length=100)),
            ],
        ),
            migrations.DeleteModel(
            name='locations',
        ),
    ]
