# Generated by Django 5.1.2 on 2024-11-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pontodescarte_delete_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='locations',
        ),
    ]
