# Generated by Django 5.1.3 on 2024-11-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='question',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
